var annotated_dup =
[
    [ "Chicken", "namespaceChicken.html", [
      [ "BaseChicken", "classChicken_1_1BaseChicken.html", "classChicken_1_1BaseChicken" ],
      [ "ChickenFactory", "classChicken_1_1ChickenFactory.html", "classChicken_1_1ChickenFactory" ]
    ] ],
    [ "DifficultyCalculator", "namespaceDifficultyCalculator.html", [
      [ "DifficultyCalculator", "classDifficultyCalculator_1_1DifficultyCalculator.html", "classDifficultyCalculator_1_1DifficultyCalculator" ],
      [ "DifficultyCalculatorFactory", "classDifficultyCalculator_1_1DifficultyCalculatorFactory.html", "classDifficultyCalculator_1_1DifficultyCalculatorFactory" ],
      [ "EasyDifficultyCalculator", "classDifficultyCalculator_1_1EasyDifficultyCalculator.html", "classDifficultyCalculator_1_1EasyDifficultyCalculator" ],
      [ "HardDifficultyCalculator", "classDifficultyCalculator_1_1HardDifficultyCalculator.html", "classDifficultyCalculator_1_1HardDifficultyCalculator" ],
      [ "MediumDifficultyCalculator", "classDifficultyCalculator_1_1MediumDifficultyCalculator.html", null ],
      [ "SpawnOrder", "classDifficultyCalculator_1_1SpawnOrder.html", "classDifficultyCalculator_1_1SpawnOrder" ]
    ] ],
    [ "RoundManager", "namespaceRoundManager.html", [
      [ "DifficultyTable", "classRoundManager_1_1DifficultyTable.html", "classRoundManager_1_1DifficultyTable" ],
      [ "RoundManager", "classRoundManager_1_1RoundManager.html", "classRoundManager_1_1RoundManager" ]
    ] ],
    [ "BaseMenu", "classBaseMenu.html", "classBaseMenu" ],
    [ "BaseTower", "classBaseTower.html", "classBaseTower" ],
    [ "Bullet", "classBullet.html", "classBullet" ],
    [ "ChickenWalkTest", "classChickenWalkTest.html", "classChickenWalkTest" ],
    [ "DearGodOhLordThatGuyIsHuge", "classDearGodOhLordThatGuyIsHuge.html", "classDearGodOhLordThatGuyIsHuge" ],
    [ "DifficultySelectionMenu", "classDifficultySelectionMenu.html", null ],
    [ "Frank", "classFrank.html", "classFrank" ],
    [ "Frankest", "classFrankest.html", "classFrankest" ],
    [ "HealthBar", "classHealthBar.html", "classHealthBar" ],
    [ "HeavyBulletBuilder", "classHeavyBulletBuilder.html", "classHeavyBulletBuilder" ],
    [ "IBulletBuilder", "interfaceIBulletBuilder.html", "interfaceIBulletBuilder" ],
    [ "Level", "classLevel.html", "classLevel" ],
    [ "LevelManager", "classLevelManager.html", "classLevelManager" ],
    [ "LevelSelectionMenu", "classLevelSelectionMenu.html", null ],
    [ "LevelSelector", "classLevelSelector.html", "classLevelSelector" ],
    [ "LoadLevelTest", "classLoadLevelTest.html", null ],
    [ "LoseMenu", "classLoseMenu.html", "classLoseMenu" ],
    [ "Main", "classMain.html", "classMain" ],
    [ "Main_menu", "classMain__menu.html", null ],
    [ "MainMenu", "classMainMenu.html", "classMainMenu" ],
    [ "Map", "classMap.html", "classMap" ],
    [ "MultiPath", "classMultiPath.html", "classMultiPath" ],
    [ "MultipathTest", "classMultipathTest.html", "classMultipathTest" ],
    [ "Path", "classPath.html", "classPath" ],
    [ "PathFollow2d", "classPathFollow2d.html", "classPathFollow2d" ],
    [ "PauseMenu", "classPauseMenu.html", "classPauseMenu" ],
    [ "RapidBulletBuilder", "classRapidBulletBuilder.html", "classRapidBulletBuilder" ],
    [ "Shop", "classShop.html", "classShop" ],
    [ "StandardBulletBuilder", "classStandardBulletBuilder.html", "classStandardBulletBuilder" ],
    [ "Tower1", "classTower1.html", "classTower1" ],
    [ "Tower1Factory", "classTower1Factory.html", "classTower1Factory" ],
    [ "Tower2", "classTower2.html", "classTower2" ],
    [ "Tower2Factory", "classTower2Factory.html", "classTower2Factory" ],
    [ "Tower3", "classTower3.html", "classTower3" ],
    [ "Tower3Factory", "classTower3Factory.html", "classTower3Factory" ],
    [ "Tower4", "classTower4.html", "classTower4" ],
    [ "Tower4Factory", "classTower4Factory.html", "classTower4Factory" ],
    [ "Tower5", "classTower5.html", "classTower5" ],
    [ "Tower5Factory", "classTower5Factory.html", "classTower5Factory" ],
    [ "TowerFactory", "classTowerFactory.html", "classTowerFactory" ],
    [ "TowerPlacement", "classTowerPlacement.html", "classTowerPlacement" ],
    [ "Tutorial", "classTutorial.html", "classTutorial" ],
    [ "WinMenu", "classWinMenu.html", "classWinMenu" ]
];